### ISSUE TITLE
bug: df_steps referenced before assignment

### ISSUE THREAD

**Issue by schumannj** [budschi/nomad-synthesis-plugin#1]
after creating a ReactorProgram entry and uploading the csv file from the tests folder I get the following error:

"exception":string"Traceback (most recent call last): File "/home/jschumann/new_nomad_test/nomad/nomad/normalizing/metainfo.py", line 38, in normalize_section normalize(archive, logger) File "/home/jschumann/new_nomad_test/.venv/lib/python3.9/site-packages/nomad_synthesis_plugin/schema_packages/crystallization.py", line 839, in normalize figure1 = self.plot_multiple_y_axes_colored(df_datalog, df_steps) UnboundLocalError: local variable 'df_steps' referenced before assignment"

**Comment by budschi** [comment]
Yes, I fixed that already locally will push a fix

**Comment by budschi** [comment]
In the meantime you can be instantiate a step

**Comment by budschi** [comment]
should work now
